### ISSUE TITLE
Problem inverting composition of `LinearMap(::SMatrix)` and `LinearMap(::RotMatrix)`

### ISSUE THREAD

**Issue by Evizero** [FugroRoames/CoordinateTransformations.jl#28] opened 2017-04-20 22:42 UTC
I ran into the following scenario that took me a while to figure out. Unsure if this is the right place for the issue.

```julia
julia> tfm = LinearMap(RotMatrix(pi/8)) # rotate
LinearMap([0.92388 -0.382683; 0.382683 0.92388])

julia> tfm2 = LinearMap(SMatrix{2,2}(.4,0,0,.8)) # scale
LinearMap([0.4 0.0; 0.0 0.8])

julia> tfm3 = compose(tfm2, tfm) # first rotate then scale
LinearMap([0.369552 -0.153073; 0.306147 0.739104])

julia> inv(tfm3) # seems broken. numbers are unexpected
LinearMap([0.369552 0.306147; -0.153073 0.739104])

julia> tfm3.m # aha! A RotMatrix instead of a SMatrix
2×2 RotMatrix{Float64}:
 0.369552  -0.153073
 0.306147   0.739104

julia> tfm3_correct = LinearMap(SMatrix{2,2}(tfm3.m)) # use SMatrix instead of RotMatrix
LinearMap([0.369552 -0.153073; 0.306147 0.739104])

julia> inv(tfm3_correct) # result now as expected
LinearMap([2.3097 0.478354; -0.956709 1.15485])
```

Am I doing something weird or do I maybe misunderstand something? Is this expected behaviour?

**Comment by Evizero** [comment] 2017-04-20 22:49
It seems that it boils down to how matrix multiplication is implemented

```julia
julia> summary(tfm.m * tfm2.m) # RotMatrix * SMatrix
"2×2 StaticArrays.SMatrix{2,2,Float64,4}"

julia> summary(tfm2.m * tfm.m) # SMatrix * RotMatrix
"2×2 RotMatrix{Float64}"
```

**Comment by Evizero** [comment] 2017-04-20 22:53
cc @timholy since this is relevant for what we are doing in https://github.com/JuliaImages/ImageTransformations.jl/pull/13

**Comment by andyferris** [comment] 2017-04-20 23:05
OK that second matrix multiplication definition of @Evizero is broken

**Comment by andyferris** [comment] 2017-04-20 23:05
As in, SMatrix * RotMatrix should always return SMatrix.

**Comment by andyferris** [comment] 2017-04-20 23:15
OK, I found the root cause. It was *StaticArrays.jl* [here](https://github.com/JuliaArrays/StaticArrays.jl/blob/v0.3.0/src/matrix_multiply.jl#L378). Sometimes it doesn't obey the `similar_type` rule by assuming the matrix type will be self-similar (if it has the same element type and size), but this isn't true of Rotations.

Interestingly, I've already fixed this for Julia v0.6. I can see about updating the Julia v0.5 version of *StaticArrays*.

**Comment by andyferris** [comment] 2017-04-20 23:32
You'll be all good when this release merges: https://github.com/JuliaLang/METADATA.jl/pull/8936

**Comment by andyferris** [comment] 2017-04-21 00:01
OK it's merged. Let me know if you have any further issues.

**Closed by andyferris** 2017-04-21 00:01 UTC

**Comment by timholy** [comment] 2017-04-21 01:12
Thanks very much, @andyferris and @Evizero!

**Comment by Evizero** [comment] 2017-04-21 06:24
Thanks!
