### ISSUE TITLE
Tests fail on v0.5 (Broken Dependency?)

### ISSUE THREAD

**Issue by ranjanan** [FugroRoames/CoordinateTransformations.jl#12] opened 2016-07-25 11:28 UTC
```
ERROR: LoadError: LoadError: syntax: unhandled expr (* s (call (core getfield) X (inert x)))
 in macro expansion; at /home/juser/.julia/v0.5/Rotations/src/math_funcs.jl:122 [inlined]                                                                           
 in anonymous at ./<missing>:?                                                                                                                                      
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)                                                                                              
 in macro expansion; at ./none:2 [inlined]                                                                                                                          
 in anonymous at ./<missing>:?                                                                                                                                      
 in eval(::Module, ::Any) at ./boot.jl:234                                                                                                                          
 in process_options(::Base.JLOptions) at ./client.jl:239                                                                                                            
 in _start() at ./client.jl:318                                                                                                                                     
while loading /home/juser/.julia/v0.5/Rotations/src/math_funcs.jl, in expression starting on line 116                                                               
while loading /home/juser/.julia/v0.5/Rotations/src/Rotations.jl, in expression starting on line 18                                                                 
ERROR: LoadError: LoadError: Failed to precompile Rotations to /home/juser/.julia/lib/v0.5/Rotations.ji                                                             
 in compilecache(::String) at ./loading.jl:505                                                                                                                      
 in require(::Symbol) at ./loading.jl:364                                                                                                                           
 in include_from_node1(::String) at ./loading.jl:426                                                                                                                
 in eval(::Module, ::Any) at ./boot.jl:234                                                                                                                          
 in require(::Symbol) at ./loading.jl:357                                                                                                                           
 in include_from_node1(::String) at ./loading.jl:426                                                                                                                
 in process_options(::Base.JLOptions) at ./client.jl:262                                                                                                            
 in _start() at ./client.jl:318                                                                                                                                     
while loading /home/juser/.julia/v0.5/CoordinateTransformations/src/CoordinateTransformations.jl, in expression starting on line 24                                 
while loading /home/juser/.julia/v0.5/CoordinateTransformations/test/runtests.jl, in expression starting on line 1  
```

**Comment by ranjanan** [comment] 2016-07-25 11:32
A Pkg.checkout of both CoordinateTransformations and Rotations resulted in a different error:
```
ERROR: LoadError: LoadError: LoadError: cannot add methods to an abstract type
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:357
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /Users/ranjan/.julia/v0.5/CoordinateTransformations/src/commontransformations.jl, in expression starting on line 29
while loading /Users/ranjan/.julia/v0.5/CoordinateTransformations/src/CoordinateTransformations.jl, in expression starting on line 52
while loading /Users/ranjan/.julia/v0.5/CoordinateTransformations/test/runtests.jl, in expression starting on line 1
```

**Comment by c42f** [comment] 2016-07-26 01:27
Thanks, @andyferris is currently working on a big refactor of Rotations which I think will address this.

**Comment by andyferris** [comment] 2016-07-26 01:33
Interesting that CoordinateTransformations doesn't work with Rotations master... I'll look into that later today!

**Comment by tkelman** [comment] 2016-08-16 02:37
CoordinateTransformations 0.2.0 failed on PackageEvaluator due to missing Quaternions:
```
ERROR: LoadError: LoadError: LoadError: UndefVarError: Quaternion not defined
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:357
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/CoordinateTransformations/src/commontransformations.jl, in expression starting on line 480
while loading /home/vagrant/.julia/v0.5/CoordinateTransformations/src/CoordinateTransformations.jl, in expression starting on line 52
while loading /home/vagrant/.julia/v0.5/CoordinateTransformations/test/runtests.jl, in expression starting on line 1
```

**Comment by andyferris** [comment] 2016-08-16 03:17
@tkelman This is Julia 0.5? CoordinateTransformations 0.3.0 was just merged into METADATA which is Julia-0.5 compatible (I guess we have to wait until PackageEvaluator runs again for that).

Anyway, this seems to be caused by a problem with the REQUIRE file not setting an upper-bound on Rotations. Should I modify the METADATA for 0.2.0 or make a new 0.2.1 which just changes the REQUIRE?

**Comment by tkelman** [comment] 2016-08-16 03:21
Modifying the requirements in METADATA for 0.2.0 would be a good after-the-fact cleanup. Hopefully users won't see it now if they upgrade to CoordinateTransformations 0.3.0, but doesn't hurt to record correct dependency information.

**Comment by andyferris** [comment] 2016-08-16 03:22
@ranjanan Now there is a tagged version of CoordinateTransformations that works on 0.5 (version 0.3.0). Since it also involves some changes to the API (partly because of changes in dependent pacakges), we will also try to make a version which works on both Julia 0.4 and Julia 0.5 (version 0.2.0 - just wait for me to fix the METADATA for that though).

**Comment by andyferris** [comment] 2016-08-16 03:22
@tkelman Thanks, will do

**Comment by c42f** [comment] 2016-08-22 02:09
Should all be working now.

**Closed by c42f** 2016-08-22 02:09 UTC
